spring:
  kafka:
    topic:
      name: "first-task"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
    consumer:
      auto-offset-reset: earliest
      group-id: test-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      enable-auto-commit: true
      auto-commit-interval: 500
    listener:
      ack-mode: time
      type: batch